name: Production

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: E2E on Chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: node-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Run cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          record: true
          headless: true
          browser: chrome
          parallel: true
          config-file: tests/cypress.json
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
