name: Production

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: CI Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: node-${{ hashFiles('**/yarn.lock') }}
      - run: pip install schemathesis
      - run: npm install yarn -g
      - run: yarn install
        if: steps.cache.outputs.cache-hit != 'true'
      - run: yarn build
      - run: yarn prettier:check
      - run: yarn test:lint
      - run: yarn test:vue
      - run: yarn test:html
      - run: yarn test:unit:ci
      - run: yarn test:unit:coverage
      - run: yarn test:e2e:ci
      - run: schemathesis run ./openapi.yml --base-url=https://ryanwilke.com/ --stateful=links --checks=all --hypothesis-deadline=None
